Pages project production branch
cloudflare/cloudflare-go pull request #1065
Opened 2022-08-26 21:26 UTC by Cyb3r-Jak3

## Description

Adds field, `production_branch`, to pages project and deployments.

## Has your change been tested?

Updated unit tests and they pass

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs. soon:tm:

2022-08-26 21:59 UTC, WalshyDev commented on pages_project.go
> +	Source              PagesProjectSource            `json:"source,omitempty"`
```suggestion
	Source              *PagesProjectSource           `json:"source,omitempty"`
```

2022-08-26 21:59 UTC, WalshyDev commented on pages_project.go
> +	WebAnalyticsToken string `json:"web_analytics_token,omitempty"`
```suggestion
	BuildCommand      string `json:"build_command"`
	DestinationDir    string `json:"destination_dir"`
	RootDir           string `json:"root_dir"`
	WebAnalyticsTag   string `json:"web_analytics_tag"`
	WebAnalyticsToken string `json:"web_analytics_token"`
```

2022-08-27 00:26 UTC, WalshyDev commented
Big API doc PR is up 😆 

Let's make sure everything is synced 👍

2022-08-27 01:54 UTC, Cyb3r-Jak3 commented
Pretty sure I got everything that is being added to the docs. Will have @WalshyDev verify

2022-08-27 10:57 UTC, WalshyDev requested changes

2022-08-27 10:57 UTC, WalshyDev commented on pages_project.go
> +	PreviewDeploymentSetting     string   `json:"preview_deployment_setting"`
This is an enum, can we have a proper type for it rather than allowing any value

2022-08-27 11:02 UTC, WalshyDev requested changes

2022-08-27 11:02 UTC, WalshyDev commented on pages_project.go
> +type D1Binding struct {
```suggestion
type R2BindingMap map[string]*R2BindingValue

type R2BindingValue struct {
	Name string `json:"name"`
}

type D1BindingMap map[string]*D1BindingValue

type D1BindingValue struct {
```

2022-08-27 11:02 UTC, WalshyDev commented on pages_project.go
```suggestion

type PreviewDeploymentSetting string

const (
	AllBranches    PreviewDeploymentSetting = "all"
	NoBranches     PreviewDeploymentSetting = "none"
	CustomBranches PreviewDeploymentSetting = "custom"
)

```

2022-08-27 11:02 UTC, WalshyDev commented on pages_project.go
> +	PreviewDeploymentSetting     string   `json:"preview_deployment_setting"`
```suggestion
	PreviewDeploymentSetting     PreviewDeploymentSetting `json:"preview_deployment_setting"`
```

2022-08-27 11:10 UTC, WalshyDev commented
I believe these are all the properties indeed

2022-08-27 22:14 UTC, WalshyDev approved these changes
lgtm

2022-08-29 00:25 UTC, jacobbednarz commented
LGTM. tracking this one against the internal PRs and lines up from what i can see, thanks!

2022-08-29 00:25 UTC, merged