load_balancing: revamp methods for consistent usage
cloudflare/cloudflare-go pull request #1084
Opened 2022-09-09 01:23 UTC by jacobbednarz

Updates the load balancing methods to:

- Ensure we have a consistent experience for user, zone and account
  level resources.
- A consistent method signature where `ctx` and `params` are available
  to all methods and filtering is performed based on the values passed
  in. See [experimental docs] for details.
- `Modify..` => `Update` to match other method conventions.

[experimental docs]: https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.mdProvide a general summary of your changes in the title above. You should
remove this overview, any sections and any section descriptions you
don't need below before submitting. There isn't a strict requirement to
use this template if you can structure your description and still cover
these points.

Unblocks https://github.com/cloudflare/terraform-provider-cloudflare/issues/1876

2022-09-09 01:27 UTC, jacobbednarz commented
@gofish this should now be in the right state. could you take another pass over this to make sure i haven't missed anything?

2022-09-14 08:37 UTC, tc80 requested changes
Looks really nice! I noticed a few places where we would error with `requested resource container <ZoneRouteLevel> is not supported for this endpoint` when in fact it is the only container supported for the endpoint.

Also, I'm wondering why we don't have any PATCH endpoints supported. Perhaps we just haven't gotten around to adding them, but curious if this is intentional 🤷

2022-09-14 08:37 UTC, tc80 commented on load_balancing.go
> +		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, ZoneRouteLevel)
```suggestion
		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, rc.Level)
```

2022-09-14 08:37 UTC, tc80 commented on load_balancing.go
> +		return []LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, ZoneRouteLevel)
```suggestion
		return []LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, rc.Level)
```

2022-09-14 08:37 UTC, tc80 commented on load_balancing.go
> +		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, ZoneRouteLevel)
```suggestion
		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, rc.Level)
```

2022-09-14 08:37 UTC, tc80 commented on load_balancing.go
> +		return fmt.Errorf(errInvalidResourceContainerAccess, ZoneRouteLevel)
```suggestion
		return fmt.Errorf(errInvalidResourceContainerAccess, rc.Level)
```

2022-09-14 08:37 UTC, tc80 commented on load_balancing.go
> +		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, ZoneRouteLevel)
```suggestion
		return LoadBalancer{}, fmt.Errorf(errInvalidResourceContainerAccess, rc.Level)
```

2022-09-15 04:55 UTC, jacobbednarz commented
> I noticed a few places where we would error with requested resource container <ZoneRouteLevel> is not supported for this endpoint when in fact it is the only container supported for the endpoint.

good find! this would have haunted future jacob during debugging for sure 😓 

> Also, I'm wondering why we don't have any PATCH endpoints supported. Perhaps we just haven't gotten around to adding them, but curious if this is intentional 

unsure, @gofish may know however, once they are publicly documented, they are welcome here!

2022-09-15 05:06 UTC, merged