Add Consecutive_up and Consecutive_down for load_balancer_monitor res…
cloudflare/cloudflare-go pull request #1380
Opened 2023-08-27 20:17 UTC by Nmishin

## Description

We can set the consecutive_down and consecutive_up parameter values for the Cloudflare Load Balancer Monitor via [API](https://developers.cloudflare.com/api/operations/load-balancer-monitors-create-monitor ) but not via terraform.

[Issue from terraform-provider-cloudflare](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1876)

## Has your change been tested?

Yes, relevant unit tests have been updated to handle the addition of this field. Additionally, changes were ran against the pre-existing test suite to verify that no regressions were introduced.

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

2023-08-27 22:03 UTC, jacobbednarz requested changes
thanks for the PR. looks good overall but we should use camel casing for the struct names.

2023-08-27 22:03 UTC, jacobbednarz commented on load_balancing.go
> +	Consecutive_up   int                 `json:"consecutive_up"`
```suggestion
	ConsecutiveUp   int                 `json:"consecutive_up"`
```

2023-08-27 22:03 UTC, jacobbednarz commented on load_balancing.go
> +	Consecutive_down int                 `json:"consecutive_down"`
```suggestion
	ConsecutiveDown int                 `json:"consecutive_down"`
```

2023-08-27 22:04 UTC, jacobbednarz commented
cc @gofish @tc80

2023-08-28 14:25 UTC, tc80 approved these changes

2023-08-28 20:15 UTC, merged